[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "simple_triton"
authors = [
    {name = "Lee Cooper", email = "lee.cooper@northwestern.edu"},
]
description = "A simple and efficient python client for the Triton Inference Server."
readme = "README.md"
requires-python = ">=3.8"
keywords = ["mlops", "digital pathology"]
license = {text = "Apache-2.0"}
dependencies = [
    "grpcio>=1.64.0",
    "histomics-stream",
    "numpy>=1.21",
    "large-image[tiff]",
    "monai",
    "pandas",
    "psutil",
    "pooch",
    "protobuf",
    "tabulate",
    "tensorflow<2.16",
    "tqdm",
    "tritonclient[all]",
]
dynamic = ["version"]

[project.optional-dependencies]
examples = ["pooch"]

[project.scripts]
inference = "simple_triton.feature_extraction:main"

[tool.setuptools]
packages = ["simple_triton", "simple_triton.io"]

[tool.setuptools_scm]

[project.urls]
"Github" = "https://github.com/PathologyDataScience/simple_triton"


