[tox]
envlist = 
  py{37,38,39,310,311}
  report
  lint
toxworkdir = {tox_root}/.tox
skip_missing_interpreters = true

[testenv]
deps =
  coverage
  pytest
commands =
    python3 -m coverage run --branch -m pytest {posargs:tests}

[testenv:lint]
deps =
  black
commands = black {posargs:.}

[testenv:report]
deps = coverage
commands =
    coverage combine
    coverage report
    coverage html

[pytest]
minversion = 6.0
addopts = -ra -q
testpaths =
    tests

[coverage:run]
concurrency = multiprocessing
data_file = .tox/coverage/.coverage
include = 
    simple_triton/*
    {envsitepackagesdir}/simple_triton/*
omit =
    tests/*
    *_test.py
    **/test_*.py
parallel = true

[coverage:paths]
source =
  simple_triton/
  {envsitepackagesdir}/simple_triton/

[coverage:html]
directory = .tox/coverage/coverage.html