from google.protobuf.json_format import MessageToDict
import time
from tritonclient.utils import InferenceServerException


def instance_group(count, kind="KIND_GPU", gpus=None):
    """Generates an instance count dictionary for use in a model config.

    A Triton configuration allows specification of resources used to serve a
    model. The instance group specifies the number of concurrent instances of
    a model to serve for a given set of resources. Resources can specify cpu
    or gpu hosting, or specific gpus. See Triton documentation for more
    details.

    Parameters
    ----------
    count : int
        The number of model instances to run concurrently.
    kind : str
        One of "KIND_GPU" for gpu serving, or "KIND_CPU" for cpu serving.
        Default value of "KIND_GPU" specifies that `count` models be hosted
        on each available gpu.
    gpus : list of int
        If specified, `count` instances will be hosted on each of the listed
        gpus. For example, [0, 1] would specify serving on gpus zero and one.
        Default value of `None` means that `count` instances will be served on
        each available gpu.
    """


def model_config(client, model_name):
    """Queries model config to retrieve triton model configuration.

    The model configuration defines serving parameters like maximum batch size,
    dynamic batching, maximum queue delay, and maps instances to system cpu and
    gpu resources.

    Parameters
    ----------
    client : tritonclient.grpc.InferenceServerClient
        A remote-procedure call client for the triton server.
    model_name : string
        The name of the model to query as registered in triton.

    Returns
    -------
    config : dict
        A dictionary describing the model configuration. See Triton
        documentation for more details.
    """

    # get model config
    config = MessageToDict(client.get_model_config(model_name))

    return config["config"]


def model_idle(client, model_name, idle=1000.0):
    """Determines if a model is idle based on time of last inference.

    Since we cannot query the model queue size of pending requests, we
    determine if a model is idle based on the time elapsed since the last
    completed inference.

    Parameters
    ----------
    client : tritonclient.grpc.InferenceServerClient
        A remote-procedure call client for the triton server.
    model_name : string
        The name of the model to query as registered in triton.
    idle : float
        The time window (milliseconds) after the last inference when a model
        is considered idle. The default value is a model is idle after 1000
        milisecodns have elapsed since the last inference.

    Returns
    -------
    status : bool
        Returns True is model is idle.
    """
    # time.sleep(.01)
    # use the client to get model statistics
    model_stats = client.get_inference_statistics(model_name)

    # convert from protobuffer to dict
    model_stats = MessageToDict(model_stats)

    try:
        print(f'lastInference={model_stats["modelStats"][0]["lastInference"]}')
        # calculate time elapsed since last inference (milliseconds)
        delta = round(time.time() * 1000) - int(
            model_stats["modelStats"][0]["lastInference"]
        )
        print(f"delta={delta}, idle={idle}")
        # return idle status
        return delta > idle
    except:
        print("last inference value not found")
        return True


def model_metadata(client, model_name):
    """Queries model metadata to retrieve model input/output signature.

    Parameters
    ----------
    client : tritonclient.grpc.InferenceServerClient
        A remote-procedure call client for the triton server.
    model_name : string
        The name of the model to query as registered in triton.

    Returns
    -------
    metadata : dict
        A dictionary describing the name, shape, and type of inputs and
        outputs, as well as maximum batch size.
    """

    # get model metadata
    metadata = MessageToDict(client.get_model_metadata(model_name))  # pragma: no cover

    return metadata  # pragma: no cover


def load_model(
    client,
    client_close,
    model_name,
    config=None,
    retries=5,
    wait=10e-3,
    block=False,
    timeout=1.0,
    verbose=True,
    model_dicts={},
    idle_check=False,
):
    """Load a model or update a model configuration on the Triton server.

    If the model is not loaded on the server, this model will attempt to load
    the model from the repository. If the config is provided, the model will be
    loaded with the provided config. If the config is not provided, the config
    will be auto generated by Triton. Calling this function for a loaded model
    will re-load the model with the provided config. In this case the model
    will be checked to see if it is idle before re-loading. This function will
    raise exceptions if there is an invalid configuration, or if problems are
    encountered loading or unloading the model.

    Parameters
    ----------
    client : tritonclient.grpc.InferenceServerClient
        A remote-procedure call client for the triton server.
    model_name : string
        The name of the model to query as registered in triton.
    config : dict
        A dictionary defining the model configuration defining the input/output
        names and type and model resources. Default value of None will result
        in Triton generating a configuration. See Triton documentation for more
        details.
    retries : int
        The maximum number of attempts for each request. Default value is 5.
    wait : float
        The time to wait between failed attempts. Default value is 0.1 seconds.
    block : bool
        If True, block until the model is idle. See check_stats() for model
        idle definition. Default value is True.
    timeout : float
        The timeout limit for waiting for model idle status. Default value is
        1 second.
    verbose : bool
        If True the function will emit status messages to stdout. Default value
        is False.
    """

    # execute all client calls in a try block to catch exceptions
    def server_check(client):
        # initialize attempts
        attempts = 0
        while True:
            try:
                # 1
                if not client.is_server_ready():
                    attempts += 1
                    if attempts > retries:
                        raise Exception(
                            "Triton server is not ready. Retry limit reached"
                        )
                    else:
                        time.sleep(wait)
                        continue
                else:
                    break
            except InferenceServerException as e:
                # raise  # uncomment after testing
                break  # keep this line for testing only

    def model_check(config=None):
        # initialize attempts
        attempts = 0
        while True:
            try:
                # 2
                if client.is_model_ready(model_name) and config is None:
                    if verbose:
                        print(f"load_model(): {model_name} is already loaded.")
                    return
                # 3
                if not client.is_model_ready(model_name):
                    if config is None:
                        if verbose:
                            print(
                                f"load_model(): {model_name} is not loaded. Loading with auto-config."
                            )
                        client.load_model(model_name)
                        return
                    # 4
                    else:
                        if verbose:
                            print(
                                f"load_model(): {model_name} is not loaded. Loading with provided config."
                            )
                        client.load_model(model_name, config)
                        return
                # 5 : check if model is idle and can be unloaded
                elif client.is_model_ready(model_name) and config is not None:
                    if verbose:
                        print(
                            f"load_model(): {model_name} is loaded. Re-loading with provided config."
                        )
                    if model_idle(client, model_name):
                        client.unload_model(model_name)
                        client.load_model(model_name, config)
                        return
                    # 6 ; if not idle, either increment attempts or check timeout
                    if not block:
                        print("***Block Secton***")
                        attempts += 1
                        if attempts > retries:
                            raise Exception(
                                f"Model {model_name} not idle. Retry limit reached."
                            )
                        time.sleep(wait)
                        continue
                    else:
                        if attempts == 0:
                            start = time.time()
                            attempts += 1
                        if time.time() - start > timeout:
                            raise Exception(
                                f"Model {model_name} not idle. Block timeout elapsed."
                            )
            except InferenceServerException as e:
                raise

    if idle_check == False:
        server_check(client_close)  # Server is not ready

        server_check(
            client
        )  # 1: server should be ready before models can be manipulated

        model_check(
            config=None
        )  #  2: model is loaded and configuration not provided - do nothing

        client.unload_model(model_name)  # to make sure load model check is executed

        model_check(config=None)  # 3: model is not loaded - attempt to load

        client.unload_model(model_name)  # to make sure load model check is executed

        model_check(
            config
        )  # 4: model is not loaded - attempt to load with provided config

        model_check(
            config
        )  # 5. model is loaded and idle - reload model and with provided config

        # # spawn inference process make model not idle

    else:  # pragma: no cover
        for i in range(1):
            if idle_check == True:
                print("idle check = True")
                model_check(
                    config
                )  # 6. model is loaded and not idle - either increment attempts or check timeout
                time.sleep(1)
